### ISSUE TITLE
Container type should not be basket

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/ISPyB#111]
upon creation of a new container propose SPINE, UNIPUCK as in EXI since basket is not recognised when using EXI to fill the sample changers in the prepare experiment appli.

This should be done in these interfaces :
- create puck
- fill shipment online
- Edit container from view shipment interface (that's the most important and easy to fix)
- for csv/excel template upload ; would that be too ugly to leave the field of container type empty and then assign the 
value upon loading to SPINE or UNIPUCK if less or more than 10 samples are found in the container? That's ugly but I am not sure you want to add complexity in the csv file itself? and the excel template file?
![capture](https://cloud.githubusercontent.com/assets/25433590/26621969/0008963a-45e9-11e7-90ac-6a6745a7bc7c.PNG)
![capture1](https://cloud.githubusercontent.com/assets/25433590/26621975/056a6f2c-45e9-11e7-96f0-1b8aaf76b721.PNG)
![capture2](https://cloud.githubusercontent.com/assets/25433590/26621976/058a503a-45e9-11e7-9025-04b95b8d12df.PNG)

**Comment by delageniere** [comment]
If 10 or less samples are found in the container then it is assigned as SPINE
If more than 10 it is assigned as UNIPUCK
