### ISSUE TITLE
Upgrade ispyb to be deployed with Wildfly10

### ISSUE THREAD

**Issue by belkassaby** [ispyb/ISPyB#149]
Hi @KarlLevik , @kevinpetersavage , could the following branch be created : "Wildfly10-migration". I'd like to make a pull-request on a branch with that name : see [commit 5422197](https://github.com/belkassaby/ISPyB/commit/54221974675d37bd68592edb61345bca0d7aa403)

**Comment by KarlLevik** [comment]
@belkassaby We'll see if we can get you the necessary privileges so you can do it.

**Comment by belkassaby** [comment]
great thanks!

**Comment by belkassaby** [comment]
thanks!

**Comment by dsclassen** [comment]
any updates on this?

**Comment by delageniere** [comment]
Yes, the last versions of ISPyB are deployable on WF 10

**Comment by delageniere** [comment]
See the closed issue : #156 
I have the impression we can close this issue but it may be related to s special configuration at DLS ?
