### ISSUE TITLE
Error adding a sample to a container

### ISSUE THREAD

**Issue by pmurphyfr** [ispyb/ISPyB#151]
POST
http://ispyvalid.esrf.fr:8080/ispyb/ispyb-ws/rest/9de059b4af1eee832bda07bbdddc5f57e69cc790/proposal/mx1819/shipping/307177/dewar/310471/puck/333942/save

With the following data
{
	"containerId": 333942,
	"code": "AA040A",
	"containerType": "Spinepuck",
	"capacity": 10,
	"beamlineLocation": null,
	"sampleChangerLocation": null,
	"containerStatus": null,
	"timeStamp": "Aug 29, 2017 11:18:09 AM",
	"barcode": null,
	"sampleVOs": [{
		"name": "PDMN_CD020194_B01-3",
		"code": "106947525359a0103e5b41a",
		"location": 1,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "20170426_Pdomain",
				"acronym": "PDMN"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}, {
		"name": "PDMN_CD020194_C01-3",
		"code": "157664431459a01047efc4a",
		"location": 2,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "20170426_Pdomain",
				"acronym": "PDMN"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}, {
		"name": "PDMN_CD020194_D01-3",
		"code": "142211348259a0104f4096a",
		"location": 3,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "20170426_Pdomain",
				"acronym": "PDMN"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}, {
		"name": "PDMN_CD020194_E01-3",
		"code": "181281554859a01058ecfc2",
		"location": 4,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "20170426_Pdomain",
				"acronym": "PDMN"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}, {
		"name": "PDMN_CD020194_F01-3",
		"code": "171619487059a0105f9bd6d",
		"location": 5,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "20170426_Pdomain",
				"acronym": "PDMN"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}]
}

**Comment by antolinos** [comment]
Hi @pmurphyfr,

I looked into the problem and such protein acronym does not exist for proposal mx1819. That is the reason of the error.

**Comment by antolinos** [comment]
Reopen if necessary
