### ISSUE TITLE
Error adding dewar code

### ISSUE THREAD

**Issue by pmurphyfr** [ispyb/ISPyB#152]
Post
http://ispyvalid.esrf.fr:8080/ispyb/ispyb-ws/rest/d1f66bf833f3d18d771308b636cddb0ccd76dcc4/proposal/mx1834/shipping/307179/dewar/save
with the following
{
	"code": "Dewar_1",
	"transportValue": 4,
	"storageLocation": "-80",
	"comments": "",
	"shippingId": 307179
}

Return {dewarId: 310473, code: null ...

**Comment by antolinos** [comment]
Hi @pmurphyfr,

Problem here is that shippingId 307179 is not associated to proposal mx1834.
Reopen if necessary,
Cheers,
A.
