### ISSUE TITLE
forceSpaceGroup not updating the Spacegroup in shipment

### ISSUE THREAD

**Issue by pmurphyfr** [ispyb/ISPyB#153]
Post
https://wwws.esrf.fr/ispyb/ispyb-ws/rest/0d5344d271070b5381d1eb03313dc5838796a8e6/proposal/mx1834/shipping/308636/dewar/312855/puck/343055/save

with the following
{
	"containerId": 343055,
	"code": "AA000A",
	"containerType": "Spinepuck",
	"capacity": 10,
	"beamlineLocation": null,
	"sampleChangerLocation": null,
	"containerStatus": null,
	"timeStamp": "Aug 29, 2017 11:55:29 AM",
	"barcode": null,
	"sampleVOs": [{
		"name": "Lyso_CD011801_B02-2",
		"code": "37152667160015dd157cd4e",
		"location": 10,
		"crystalVO": {
			"spaceGroup": "Unknown",
			"proteinVO": {
				"name": "lyzozyme",
				"acronym": "Lyso"
			}
		},
		"diffractionPlanVO": {
			"forcedSpaceGroup": "P1",
			"requiredMultiplicity": 4,
			"preferredBeamDiameter": 50,
			"kappaStrategyOption": 0,
			"numberOfPositions": 1,
			"radiationSensitivity": 0,
			"experimentKind": "MXPressE"
		}
	}]
}

forcedSpaceGroup is set to "P1" in the shipment on ISPyB but the spacegroup is set to Unknown

**Comment by antolinos** [comment]
Hi @pmurphyfr,

After discussion with @olofsvensson it seems that forcedSpaceGroup was not used in the workflows. This will be changed soon.

Related to ISPyB forceSpaceGroup is written in the database.

Cheers,
A.
