### ISSUE TITLE
New workflow types

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/ISPyB#154]
I need to add the following new workflow types:
'MXPressH'
'MXPressP'
'MXPressP_SAD'
'MXPressR'
'MXPressR_180'
'MXPressR_dehydration'
'MXScore'
'MeshAndCollect'
'MeshAndCollectFromFile'

**Comment by olofsvensson** [comment]
Pull request: 
https://github.com/ispyb/ISPyB/pull/155

**Comment by StephMonaco** [comment]
Would it be possible to add a tooltip for each WF (from the ISPYB interface) with a few words like for MXpressO: Xray cent- 180deg - 0.2deg osc -2A or already obs reso

**Comment by olofsvensson** [comment]
I have opened a new issue for the tooltips: #164
