### ISSUE TITLE
Update the ProposalHasPerson table from User Portal webservice to enable data confidentiality

### ISSUE THREAD

**Issue by delageniere** [ispyb/ISPyB#169]
In the future, the login will be done also with individual user accounts, in this case, only data related to the proposals linked to the user who logs in should be made available.

The User Portal will provide the list of authorized users for a proposal, and will also provide the modifications in this list because a user can be removed from a proposal.

The ProposalHasPerson table will be updated accordingly calling the webservice on a planned base.

Note that a "light" person could be entered only with minimal data : only name, firstname , login and siteId to identify uniquely the person but to avoid adding/updating also labs (only needed for co-proposers, but not for participants).

**Comment by delageniere** [comment]
The table is filled with list of proposers/participants for now and on ESRF side we are waiting for the individual accounts to go further and use this table for authorization.

**Comment by hormiai76** [comment]
We are populating the ProposalHasPerson table with all the co-proposers and all the participants of the session using the MAXIVWebService and it works fine for us having individual user login at MAX IV
Alberto Nardella

**Comment by delageniere** [comment]
This is done also on ESRF side, the table is populated but not yet used.
