### ISSUE TITLE
SITE_ATTRIBUTE is unrecogniozed in "Prepare experiment" pages

### ISSUE THREAD

**Issue by hormiai76** [ispyb/ISPyB#176]
Hi,

I'm trying to show in the correct way the "Prepare experiment" pages but the **SITE_ATTRIBUTE** seems to be unrecognized. 
If I added **`<%@ page isELIgnored="false" %>`** to the beginning of the pages it seems that it'is all right and MAXIV labels appear. Maybe I need to configure something in order to have the **SITE_ATTRIBUTE** variable in all the pages... 
In the login page and in the header I can use the variable without problem but in the **fillSampleCharger.jsp**, **mxcubeHelp.jsp**, **prepareHelp.jsp** I need to add this extra line and I'm not sure if it's a bug or not.
Regards,
Alberto Nardella

**Comment by delageniere** [comment]
Hi,
Yes, this reminds me of a known issue, but I thought it was fixed ...
 in the jsps you have to add the <%@ page isELIgnored="false" %> I think it is to authorize the reading of the Constants class which is needed to use the SITE_ATTRIBUTE.
I will investigate a bit further but you should be ok adding this.
Cheers,
Solange

**Comment by delageniere** [comment]
This was indeed the problem and the SITE ATTRIBUTE was not interprted, I added <%@ page isELIgnored="false" %> and tested it. It is ok now. 
It is merged on the master branch.
