### ISSUE TITLE
Return date for shipment as well as parameters form detector to be retrieved from webservices

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/ISPyB#18]
There are some parameters needed in some of the current WebServices:

----------------------------------------------------------------------------------------------------------
Method: **EXI.getDataAdapter().proposal.shipping.getShipment**

Parameter: 

- Return date

Currently we have creationDate, dateOfShippingToUser, deliveryAgentDeliveryDate. But we need a returnDate just like in ispyb:

![image](https://cloud.githubusercontent.com/assets/22632506/22730889/09bd8210-ede9-11e6-8bfb-a29402634d92.png)

----------------------------------------------------------------------------------------------------------
Method: **EXI.getDataAdapter().proposal.shipping.getDewarTrackingHistory**

Parameter: 

- Outbound courier

Currently we have Shipping_returnCourier. But we need an outboundCourier just like in ispyb:

![image](https://cloud.githubusercontent.com/assets/22632506/22730954/4ff4b7e4-ede9-11e6-8cbf-393e8b257f8b.png)

----------------------------------------------------------------------------------------------------------
Method: **EXI.getDataAdapter().mx.sample.getSamplesByContainerId**

Parameter: 

- Container_containerCode

----------------------------------------------------------------------------------------------------------
Method: **EXI.getDataAdapter().mx.dataCollection.getByAcronymList**

We need parameters for the detectors:

![image](https://cloud.githubusercontent.com/assets/22632506/22731237/389d2ed6-edea-11e6-9662-edb9b1d4f049.png)

**Comment by antolinos** [comment]
Container_code already in the query
