### ISSUE TITLE
move documentation to plain text?

### ISSUE THREAD

**Issue by dsclassen** [ispyb/ISPyB#189]
I can see that significant effort was put into formatting the ISPyB_developsGuide.doc file, but it is binary and changes to it are not easily determined via git – at least I'm not aware of how to do this. 

Would it be possible/desirable to migrate the documentation from *.doc to something that will be more easily tracked in git? Maybe we could activate the github wiki?

Thanks,
Scott

**Comment by jlmuir** [comment]
On 11/10, Scott Classen wrote:
> Would it be possible/desirable to migrate the documentation from *.doc to something that will be more easily tracked in git?

+1

**Comment by antolinos** [comment]
Yes, I totally agree.

Cheers,
A.

2017-11-14 17:05 GMT+01:00 J. Lewis Muir <notifications@github.com>:

**Comment by delageniere** [comment]
Yes, that's a good idea, and it would also help clean/check the doc once 
more.
Cheers,
Solange
