### ISSUE TITLE
New proposal ?

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/ISPyB#192]
When a new proposal is created the proposal doesn't belong into the proposal table before there is a first log-in into ISPYB. Why is this so? Is it really necessary? and if yes can this process be implemented in EXI since today the log-in in EXI is not possible with a new proposal.
Thanks
Stephanie

**Comment by delageniere** [comment]
Currently a new proposal is automatically retrieved from SMIS if it is a 
MX, FX, or IX.
