### ISSUE TITLE
"mvn install" modifies file under version control

### ISSUE THREAD

**Issue by jlmuir** [ispyb/ISPyB#200]
I start with a clean ISPyB Git repo working tree:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

I run `mvn install`, and now Git shows a change that I did not make:

```
$ git status
On branch master
Changed but not updated:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ispyb-ui/src/main/webapp/js/ispyb/min/ispyb-bx.js

no changes added to commit (use "git add" and/or "git commit -a")
```

A build should not dirty the working tree.

**Comment by antolinos** [comment]
I agree. Do you think min folder should be included into the gitignore list?

**Comment by jlmuir** [comment]
I didn't look closely; I was hoping someone would just know what to do.  If the `min` directory is created at build time to contain the minimized JavaScript, then I'd say, yes, just adding it to Git's ignore list would be fine.  However, I see that the `min` directory currently exists in the repository and contains two files: `ispyb-bx.js` and `ispyb-mx.js`, so I'm less sure about what's going on.  Are those just minimized versions of some other files that are also in the repo?  If so, then if it's OK to build the minimized versions at build time, removing them from the repo and having Git ignore the `min` directory seems fine to me.

Another approach might be to generate the minimized JavaScript files under the `target` tree.  However, there may be cases where this wouldn't make the most sense or work the best, and I haven't looked closely at exactly what's happening with these minimized JavaScript files to say.  Thanks!
