### ISSUE TITLE
Why does ispyb-bcr not have ispyb-parent as its parent?

### ISSUE THREAD

**Issue by jlmuir** [ispyb/ISPyB#215]
I noticed that `ispyb-{bcr-ear,ear,ejb,ui,ws}` all have `ispyb-parent` as their parent, but not `ispyb-bcr`; why is that?  I don't know very much about Maven, so maybe this is intentional, but I'd like to understand.  Thanks!

**Comment by delageniere** [comment]
That's a mistake ! strange because it should belong to ispyb-parent and I never noticed it.
Should be fixed !
