### ISSUE TITLE
SD deployment profile?

### ISSUE THREAD

**Issue by jlmuir** [ispyb/ISPyB#219]
What is the `SD` profile in `ispyb-ui/pom.xml`?  It's grouped with the deployment profiles (i.e., `DEV` and `PROD`), but according to the ISPyB Developers Guide, there is no deployment profile by that name.

Is it perhaps the initials of a developer?  If so, I'm thinking that rather than each developer adding their own development profile to that file (or any other), it would be better for each developer to modify the existing `DEV` profile according to their needs and manage that as a local change (e.g., in Git as a local branch of customizations).

I'm asking because I'd like to remove site-specific values from things that are not site-specific.  Thanks!

**Comment by delageniere** [comment]
Well spotted, it's a test with my personal profile which should not be there for sure !
