### ISSUE TITLE
Old ISPyB interface for SAXS doesn't work anymore

### ISSUE THREAD

**Issue by DimaMolod** [ispyb/ISPyB#261]
Some problem with http://ispyb.embl-hamburg.de/ispyb/user/dataadapter.do?reqCode=getProposal
**ISPyB: Retrieving** never ends (not only for "prepare experiment" section but for all sections).
An old version of ISPyB works fine.
Details below...

Request Method: POST
Status Code: 500 Internal Server Error

![screenshot from 2018-03-27 16-31-29](https://user-images.githubusercontent.com/33123184/37974503-5d4645aa-31dd-11e8-9751-2adf23be290c.png)

{,…}
message
:
"org.hibernate.exception.SQLGrammarException: could not extract ResultSet"
trace
:
"javax.ejb.EJBException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet↵	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:187)↵	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:277)↵	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:327)↵	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:239)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.remote.EJBRemoteTransactionPropagatingInterceptor.processInvocation(EJBRemoteTransactionPropagatingInterceptor.java:79)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:43)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.deployment.processors.EjbSuspendInterceptor.processInvocation(EjbSuspendInterceptor.java:44)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:66)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)↵	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:634)↵	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)↵	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)↵	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:195)↵	at org.jboss.as.ejb3.remote.LocalEjbReceiver.processInvocation(LocalEjbReceiver.java:261)↵	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:184)↵	at org.jboss.ejb.client.EJBObjectInterceptor.handleInvocation(EJBObjectInterceptor.java:58)↵	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:186)↵	at org.jboss.ejb.client.EJBHomeInterceptor.handleInvocation(EJBHomeInterceptor.java:83)↵	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:186)↵	at org.jboss.ejb.client.TransactionInterceptor.handleInvocation(TransactionInterceptor.java:42)↵	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:186)↵	at org.jboss.ejb.client.ReceiverInterceptor.handleInvocation(ReceiverInterceptor.java:125)↵	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:186)↵	at org.jboss.ejb.client.EJBInvocationHandler.sendRequestWithPossibleRetries(EJBInvocationHandler.java:255)↵	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:200)↵	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:183)↵	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:146)↵	at com.sun.proxy.$Proxy169.findByProposal(Unknown Source)↵	at ispyb.client.biosaxs.dataAdapter.BiosaxsActions.findShipmentsByProposal(BiosaxsActions.java:364)↵	at ispyb.client.biosaxs.dataAdapter.BiosaxsDataAdapterAction.getProposalData(BiosaxsDataAdapterAction.java:1139)↵	at ispyb.client.biosaxs.dataAdapter.Biosa…yStatement(Loader.java:1863)↵	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)↵	at org.hibernate.loader.Loader.doQuery(Loader.java:910)↵	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)↵	at org.hibernate.loader.Loader.doList(Loader.java:2554)↵	at org.hibernate.loader.Loader.doList(Loader.java:2540)↵	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)↵	at org.hibernate.loader.Loader.list(Loader.java:2365)↵	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)↵	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1718)↵	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)↵	at ispyb.server.common.services.shipping.Shipping3ServiceBean.findByProposal(Shipping3ServiceBean.java:361)↵	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)↵	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)↵	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)↵	at java.lang.reflect.Method.invoke(Method.java:483)↵	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)↵	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:82)↵	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:93)↵	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)↵	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)↵	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)↵	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.component.interceptors.NonPooledEJBComponentInstanceAssociatingInterceptor.processInvocation(NonPooledEJBComponentInstanceAssociatingInterceptor.java:59)↵	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)↵	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:275)↵	... 95 more↵Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'dewarvos3_.isReimbursed' in 'field list'↵	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)↵	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)↵	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)↵	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)↵	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)↵	at com.mysql.jdbc.Util.getInstance(Util.java:386)↵	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)↵	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)↵	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)↵	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)↵	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)↵	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)↵	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)↵	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2318)↵	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)↵	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)↵	... 137 mor

**Comment by antolinos** [comment]
Hi @delageniere,

It seems there is a problem with isReimbursed. Could you please check it?

**Comment by delageniere** [comment]
Hi,
Did you update the database using the last update scripts which contain the new fields for reimburse dewar ?

**Comment by delageniere** [comment]
Hi,
Did you update the database using the last update scripts to add the new field about reimbursed dewars ?

**Comment by delageniere** [comment]
Hi,
Did you update the database using the last update scripts to add the new field about reimbursed dewars ?

**Comment by delageniere** [comment]
Hi

**Comment by DimaMolod** [comment]
Hi,
no, looks like I didn't...
thanks for the hint!

**Comment by IvarsKarpics** [comment]
Hi @DimaMolod ,

I updated ispyb DB. Can you check now?

**Comment by DimaMolod** [comment]
Hi @IvarsKarpics ,
everything works just fine, I had that issue with my local db
