### ISSUE TITLE
Info about Labels pdf template

### ISSUE THREAD

**Issue by hormiai76** [ispyb/ISPyB#284]
Hi @delageniere,
we need to update the labels pdf template with the MAX IV address instead of the old Maxlab one.
Is there any free tool we can use to do it? I would like to avoid to pay an Adobe LiveCycle Designer license only to change a template.
Regards,
Alberto

**Comment by delageniere** [comment]
Hi Alberto,
I do not know any free tool, because someone in our group has got a licence.
May be you could use the trial version of Adobe Writer.
Regards,
Solange

**Comment by hormiai76** [comment]
Thank you Solange,
You can close the ticket
