### ISSUE TITLE
Problems with ispyb.log and server.log files

### ISSUE THREAD

**Issue by hormiai76** [ispyb/ISPyB#304]
Hi all,
I detected in our production environment that the size of the log files don't restart from 0 after the log rotation and this affects the disk space.
I created a cronjob task to zip both logs every night and remove the zipped files after a week but it doesn't work if the the ispyb.log and server.log sizes are both **25GB**!
I use the _standalone.xml.sample_ to configure our wildfly server without change the logging part and then I set **INFO** instead of **DEBUG** in the ISPYB log but it doesn't solve the problem.
Any suggestion?
Regards,
Alberto Nardella

**Comment by hormiai76** [comment]
Hi @delageniere,
could you share with me the logging part of your standalone.xml file of the production server?
We use a Wildfly8.
Regards,
Alberto

**Comment by delageniere** [comment]
25 GB is really huge ! I checked how large are our log files to tell you:
server.log is around 100M and ispyb.log is around 20 M
Cheers,
Solange

**Comment by hormiai76** [comment]
Hi  Solange,
Thank you for the help. I fixed it following your logging.txt file
Alberto
