### ISSUE TITLE
Missing IHR proposals at ESRF

### ISSUE THREAD

**Issue by maaeli** [ispyb/ISPyB#305]
Hi,

the list of schedueled IHR sessions as seen in ISPYB and EXI (at least for BM29) is incomplete (at least for BM29): it shows IH-LS experiments, but none of the other types, in particular IH-MX and IH-SC.

Best,
Martha

**Comment by delageniere** [comment]
Changes have been made also on SMIS side, wait for a deploy of SMIS in prod
