### ISSUE TITLE
Excel template logo

### ISSUE THREAD

**Issue by hormiai76** [ispyb/ISPyB#316]
Hi all,
I would like to create a **shipment-template_MAXIV.xlt** file with the **MAXIV  logo** to be used to upload a shipment but when I save the file  in the **Excel 97-2003 format** something goes wrong. The template is not valid anymore and the xls generated in the page is empty and unusable.
Any suggestion? 
If anyone can edit in the correct way the template without errors, is it possible to change the **ESRF logo** to the **ISPyB one**?
Regards,
Alberto Nardella

**Comment by delageniere** [comment]
Hi,
Sometimes I have troubles saving the template if I try to save it directly in the ispyb folder. If I save it in the default one, then copy it to the ispyb folder it is ok. Not sure it corresponds to your problem...

**Comment by hormiai76** [comment]
Hi Solange,
If you can update your .xlt file replacing the ESRF logo with the ISPyB one and it still works please could you then upload the file here or in the project?
Alberto

**Comment by delageniere** [comment]
Hi Alberto,
I just created a pull request with a template created from your xls file, so with the MaxIV logo inside.
Solange

**Comment by hormiai76** [comment]
Thank you

**Comment by hormiai76** [comment]
Hi Solange,
ISPyB uses the **ispyb-template6.1_shipment.xlt** template to create the **MX20170251_shipment_39.xls** file on the fly. 
I tested your xls file but the protein are not loaded. If I use the official **xlt** it works but with the ESRF logo.
Alberto

**Comment by delageniere** [comment]
Hi Alberto,
Please try with this one.
Solange

**Comment by hormiai76** [comment]
The protein combo are still empty. Using the ESRF the combo is loaded as expected.
[MX20170251_shipment_39.zip]
[MX20170251_shipment_39_ESRF_template.zip](https://github.com/ispyb/ISPyB/files/2123833/MX20170251_shipment_39_ESRF_template.zip)
(https://github.com/ispyb/ISPyB/files/2122768/MX20170251_shipment_39.zip)
