### ISSUE TITLE
Missing field crashes ISPyB for Biosaxs

### ISSUE THREAD

**Issue by antolinos** [ispyb/ISPyB#369]
Hi @DimaMolod,

pathToH5 is missing in the DB and crashes BioSAXS experiments.
https://github.com/emblsaxs/ISPyB-membrane/blob/f7e3a61623416f694378365a10740382644a1478/ispyb-ejb/db/scripts/ahead/2018_02_27_membranes_update.sql

This  solves the problem:
```
INSERT INTO SchemaStatus (scriptName, schemaStatus) VALUES ('2018_02_27_membranes_update.sql','ONGOING');

USE pydb;
ALTER TABLE Macromolecule ADD electronDensity FLOAT(7,5);
ALTER TABLE Buffer ADD electronDensity FLOAT(7,5);
ALTER TABLE Additive ADD chemFormulaHead VARCHAR (25) default '';
ALTER TABLE Additive ADD chemFormulaTail VARCHAR (25) default ''; 
ADD COLUMN `pathToH5` VARCHAR(512) NULL AFTER `comments`;

update SchemaStatus set schemaStatus = 'DONE' where scriptName = '2018_02_27_membranes_update.sql';
```

**Comment by DimaMolod** [comment]
Hi @antolinos ,
sorry for that. Apparently, I added the column manually and forgot to add it to the script.
Thanks for the help.

**Comment by delageniere** [comment]
Hi @DimaMolod and @antolinos 
I think the best is to create a new update script with the date of today to fix this and not break the update db process using the correct scripts in the order.
Thanks,
Solange
