### ISSUE TITLE
Some local contacts do not receive email through dewar tracking (BCR application)

### ISSUE THREAD

**Issue by delageniere** [ispyb/ISPyB#388]

**Comment by delageniere** [comment]
In ISPyB MX web pages, dewars are linked to a session as in EXI, parcels and dewars are not linked to a session but the shipment is linked to the session.
The BCR code has to take into account both cases.

**Comment by antolinos** [comment]
Hi @delageniere.

I think containers and dewars can not be never linked to a session as there is not sessionId in the table (dewar and container)

**Comment by delageniere** [comment]
Hi @antolinos ,
It is done through "firstExperimentId"

**Comment by antolinos** [comment]
Hum, right. Then I would suggest to rename that column and call it sessionId

**Comment by delageniere** [comment]
It was not a bug
