### ISSUE TITLE
Documentation for UserRoles on ISPyB is not clear or incomplete

### ISSUE THREAD

**Issue by antolinos** [ispyb/ISPyB#42]
Some collaborators are running into troubles when installing ISPyB in a test environment. They use LDAP but don't know where userRoles are coming from and how to use them
is it described on  ISPyB_DevelopersGuide.doc how to assign the roles to an user on ISPyB?

**Comment by delageniere** [comment]
Documentation concerning the simple authentication case should be be added, and an example of code using this simple authentication.
