### ISSUE TITLE
Missing license file?

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/ISPyB#432]
I've noticed there doesn't appear to be a license file in the repo root. I think it would make sense to have a license file.

Is there an agreed license for the ISPyB code and/or database schema? It's obviously some kind of open-source license, but which one?

**Comment by delageniere** [comment]
Hi, the licence is GNU GPL version 3 or later, it is indicated in the files header and the copy of the licence should be included somewhere. Do not remember where we put it, but I'll have a look.

**Comment by delageniere** [comment]
Found it : it is located in ispyb-ui/Documentation/licence. 
May be not the best location, we should probably move it upper in the project somewhere in the parent, or in each maven module.

**Comment by KarlLevik** [comment]
Thank you, Solange. Yes, if it's meant to be the same license for everything, then it would be nice to have it in the project root. 

I see both a GPL3+ and an LGPL3+ file in that directory, though the file headers seem to have LGPL3+. Not all the source code files have headers, though, and that is especially the case for the database schema .sql files.

Maybe not relevant, but I wonder if the license is specified in the MoU?

**Comment by KarlLevik** [comment]
Apparently, the MoU says all the software should be GNU LGPL, giving this link which currently re-directs to the 3.0 version - http://www.gnu.org/licenses/lgpl.html

**Comment by delageniere** [comment]
Licence files added in ISPyB/licence folder.
The header should be copied to all ispyb files.
