### ISSUE TITLE
What is the location and structure of XFE spectrum file?

### ISSUE THREAD

**Issue by IvarsKarpics** [ispyb/ISPyB#51]
Hi,

In the EXI there is a nice graph displaying XFE spectrum. What is the structure and location (table column) of the file to be displayed in this graph?

**Comment by antolinos** [comment]
Hi @IvarsKarpics,

Column is fittedDataFileFullPath in the table XFEFluorescenceSpectrum. File
format is a csv . Please find here attached an example.


2017-03-10 11:36 GMT+01:00 Ivars Karpics <notifications@github.com>:

**Comment by antolinos** [comment]
Hi @IvarsKarpics,

Column is fittedDataFileFullPath in the table XFEFluorescenceSpectrum. File format is a csv . Please find here attached an example.

[Uploading fitted_example.txt…]()

**Comment by IvarsKarpics** [comment]
Hi @antolinos ,

Thanks for the info. However the link to the file is not working. Can you just copy/paste few lines from the example file?

**Comment by antolinos** [comment]
"channel","Energy","counts","fit","continuum","pileup","yCo K","yCu K","yZn
K","
yCa K","yMn K","yCr K","ySe K","yS K","yNi K","yCl K","yK K","yFe K"
472,2.026112,0,2.621532e-05,0,0,0,0,0,0,0,0,0,2.621532e-05,0,4.485241e-19,0,0
473,2.030963,0,3.551456e-05,0,0,0,0,0,0,0,0,0,3.551456e-05,0,8.274722e-19,0,0
474,2.035814,0,4.785753e-05,0,0,0,0,0,0,0,0,0,4.785753e-05,0,1.518903e-18,0,0
475,2.040665,0,6.415212e-05,0,0,0,0,0,0,0,0,0,6.415212e-05,0,2.774272e-18,0,0
476,2.045516,0,8.553969e-05,0,0,0,0,0,0,0,0,0,8.553969e-05,0,5.041696e-18,0,0
477,2.050367,0,0.0001134592,0,0,0,0,0,0,0,0,0,0.0001134592,0,9.116894e-18,0,0
478,2.055217,0,0.0001496954,0,0,0,0,0,0,0,0,0,0.0001496954,0,1.640308e-17,0,0
479,2.060068,0,0.0001964687,0,0,0,0,0,0,0,0,0,0.0001964687,0,2.936615e-17,0,0
480,2.064919,0,0.000256491,0,0,0,0,0,0,0,0,0,0.000256491,0,5.230896e-17,0,0
481,2.06977,0,0.0003330964,0,0,0,0,0,0,0,0,0,0.0003330964,0,9.271483e-17,0,0
482,2.074621,0,0.000430307,0,0,0,0,0,0,0,0,0,0.000430307,0,1.635125e-16,0,0
483,2.079472,0,0.0005529255,0,0,0,0,0,0,0,0,0,0.0005529255,0,2.869152e-16,0,0
484,2.084323,0,0.000706799,0,0,0,0,0,0,0,0,0,0.000706799,0,5.009651e-16,0,0

2017-03-10 13:15 GMT+01:00 Ivars Karpics <notifications@github.com>:

**Comment by IvarsKarpics** [comment]
Thanks!
