### ISSUE TITLE
Do we have to rerun MySQL update scripts?

### ISSUE THREAD

**Issue by IvarsKarpics** [ispyb/ISPyB#73]
Hi,

I see that MySQL update scripts are changed and recommitted. Do I have to re-run the script after each change (commit)?

**Comment by antolinos** [comment]
No. Except of an error in principle one script only have to be run once. 

We have been working in the organization of the scripts in order to make:
- Keeping an ISPyB instance up to date easily
- Installing ISPyB from scratch

I think this is why they have been recommitted.

**Comment by IvarsKarpics** [comment]
Ok, clear. Thanks for answer.
You can keep the issue for some time and close it if necessary.

Cheers,
Ivars
