### ISSUE TITLE
Merge the DB schema with DLS + create new fields in existing EJBs + create new EJBs if to be used.

### ISSUE THREAD

**Issue by delageniere** [ispyb/ISPyB#77]
Run the scripts present in the project ispyb-merge-database.
For existing tables where new fields have been entered, add the new fields to the EJBs VO, and check all corresponding DAOs and services, update the finders if necessary.
For new tables, check if they are going to be used, if yes, add the corresponding EJBs : both VOs and Services.

**Comment by delageniere** [comment]
The scripts have been run and the new tables + fields + scripts belong to tag ISPyB5.
Remain to be done the java objects part for what will be used.

**Comment by antolinos** [comment]
Hi,

Where the scripts can be found? Could we reference them in this thread for the record? 
I guess this issue can be closed later on.

I have found two scripts but in merge there are 3: https://github.com/ispyb/ispyb-merge-database/tree/master/merge

https://github.com/ispyb/ISPyB/blob/ISPyB5/ispyb-ejb/db/scripts/ahead/2017_05_02_Merge_with_DLS_create.sql
https://github.com/ispyb/ISPyB/blob/ISPyB5/ispyb-ejb/db/scripts/ahead/2017_05_02_Merge_with_DLS_update.sql

**Comment by delageniere** [comment]
Hi,
The only scripts to be run are the 2 scripts:

https://github.com/ispyb/ISPyB/blob/ISPyB5/ispyb-ejb/db/scripts/ahead/2017_05_02_Merge_with_DLS_create.sql
https://github.com/ispyb/ISPyB/blob/ISPyB5/ispyb-ejb/db/scripts/ahead/2017_05_02_Merge_with_DLS_update.sql

The explanation in the issue description was just to keep note of where the scripts came from.

So when someone is cloning ISPyB 5, all the code and scripts to be run are stored as usual in ispyb-ejb/db/scripts.

**Comment by delageniere** [comment]
The issue will be closed later because we still have to add the EJBs concerning the tables we wish to use.
Or shall we open a new issue for this ?

**Comment by delageniere** [comment]
The issue will be closed now. If we decide to add new EJBs concerning the new added tables, then new issues concerning these new features shall be open.
