### ISSUE TITLE
Where are the DB update scripts?

### ISSUE THREAD

**Issue by IvarsKarpics** [ispyb/ISPyB#86]
Hi,

I see some changes in directories and scripts are moved from `update_scripts` to `ISPyB/ispyb-ejb/db/scripts/passed` and `ahead`
Sorry but this is confusing. Could you please explain this change? Or I missed some email? 
Which update scripts and from where we have to run?

Thank you in advance,
Ivars

**Comment by delageniere** [comment]
Hi,

Yes, this was a bit confusing, solved now:

For a particular tag we have:
ispyb-ejb/db/scripts/pyconfig.sql
This corresponds to the menu options, and contains both structure and data

ispyb-ejb/db/scripts /pydb.sql
This corresponds to the ISPyB metadata and contains only the database structure.

ispyb-ejb/db/scripts/schemaStatus.sql
This corresponds to the entries present in SchemaStatus table and gives an overview of the executed update scripts. 

These above creation scripts are normally updated for each tag, but if you are using the master latest version or a new branch, you may have to run the update scripts present in :
ispyb-ejb/db/scripts/ahead

-> Check before the entries in SchemaStatus table to know which scripts to execute.

The scripts already run for the current tag are in :
ispyb-ejb/db/scripts/passed

According to the version of your database, you can check the last script executed in the SchemaStatus table and then execute the missing scripts you will find in ispyb-ejb/db/scripts/ahead or in ispyb-ejb/db/scripts/passed, if your version was not updated with the latest tag.

I hope it is clearer now.
Cheers,
Solange

**Comment by IvarsKarpics** [comment]
Hi @delageniere ,

Now it is clear. Thanks!
